"""phase1_schema

Revision ID: 258b7759049c
Revises: 
Create Date: 2026-08-12 14:15:38.912042
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258b7759049c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rewards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coin_cost', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rewards_active'), 'rewards', ['active'], unique=False)
    op.create_index(op.f('ix_rewards_id'), 'rewards', ['id'], unique=False)
    op.create_index(op.f('ix_rewards_name'), 'rewards', ['name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('coin_balance', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('reward_redemptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('coins_spent', sa.Integer(), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reward_redemptions_id'), 'reward_redemptions', ['id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_redeemed_at'), 'reward_redemptions', ['redeemed_at'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_reward_id'), 'reward_redemptions', ['reward_id'], unique=False)
    op.create_index(op.f('ix_reward_redemptions_user_id'), 'reward_redemptions', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_timestamp', sa.Text(), nullable=True),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=80), nullable=True),
    sa.Column('account_name', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_amount'), 'transactions', ['amount'], unique=False)
    op.create_index('ix_transactions_amount_date', 'transactions', ['amount', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant'), 'transactions', ['merchant'], unique=False)
    op.create_index('ix_transactions_merchant_status_date', 'transactions', ['merchant', 'status', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_source_id'), 'transactions', ['source_id'], unique=False)
    op.create_index(op.f('ix_transactions_status'), 'transactions', ['status'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index('ix_transactions_user_category', 'transactions', ['user_id', 'category'], unique=False)
    op.create_index('ix_transactions_user_date', 'transactions', ['user_id', 'transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_index('ix_transactions_user_status', 'transactions', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transactions_user_status', table_name='transactions')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index('ix_transactions_user_date', table_name='transactions')
    op.drop_index('ix_transactions_user_category', table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_status'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_source_id'), table_name='transactions')
    op.drop_index('ix_transactions_merchant_status_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_merchant'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index('ix_transactions_amount_date', table_name='transactions')
    op.drop_index(op.f('ix_transactions_amount'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_reward_redemptions_user_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_reward_id'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_redeemed_at'), table_name='reward_redemptions')
    op.drop_index(op.f('ix_reward_redemptions_id'), table_name='reward_redemptions')
    op.drop_table('reward_redemptions')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_rewards_name'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_id'), table_name='rewards')
    op.drop_index(op.f('ix_rewards_active'), table_name='rewards')
    op.drop_table('rewards')
    # ### end Alembic commands ###
